apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mwc-demo.fullname" . }}
  labels:
    {{- include "mwc-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mwc-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "mwc-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /app
          env:
          - name: MWC_LOGLEVEL
            value: "{{ if .Values.debug | default false }}DEBUG{{ else }}INFO{{ end }}"
          command:
          - /usr/local/bin/gunicorn
          args:
           - --certfile=/tls/tls.crt
           - --keyfile=/tls/tls.key
           - --workers=2
           - --bind=0.0.0.0:5000
           - --timeout=90
           - --log-level={{ if .Values.debug | default false }}DEBUG{{ else }}INFO{{ end }}
           - wsgi:app
          ports:
            - name: flask
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: flask
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: flask
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mwc-certs
              mountPath: /tls
              readOnly: true
      volumes:
        - name: mwc-certs
          secret:
            secretName: {{ include "mwc-demo.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
