apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mwc-webhook
webhooks:
  - name: mwc-app-svc.mwc-demo.svc
    clientConfig:
      service:
        name: mwc-app-svc
        namespace: mwc-demo
        path: "/mutate"
      caBundle: %CA_BUNDLE%
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]
    #failurePolicy: Ignore
    #timeoutSeconds: 2
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
